import nbformat
import os
from pathlib import Path
import re

notebook_dir = Path(r'C:\Users\Echo\Desktop\modbus-detection\notebooks')

# Comprehensive translation map
translation_map = {
    "阶段": "Phase",
    "实验": "Experiment",
    "数据准备": "Data Preparation",
    "特征提取": "Feature Extraction",
    "模型训练": "Model Training",
    "评估": "Evaluation",
    "结果": "Results",
    "分析": "Analysis",
    "混淆矩阵": "Confusion Matrix",
    "准确率": "Accuracy",
    "精确率": "Precision",
    "召回率": "Recall",
    "特征重要性": "Feature Importance",
    "消融实验": "Ablation Study",
    "核心验证": "Core Validation",
    "补充实验": "Supplementary Experiments",
    "误判分析": "Error Analysis",
    "基础实验": "Baseline Experiments",
    "环境测试": "Environment Test",
    "数据采样": "Data Sampling",
    "探索": "Exploration",
    "快速测试": "Quick Test",
    "标签诊断": "Label Diagnostics",
    "质量排查": "Quality Audit",
    "协议层": "Protocol Layer",
    "时序层": "Temporal Layer",
    "业务逻辑": "Business Logic",
    "全部特征": "All Features",
    "二分类": "Binary Classification",
    "多分类": "Multi-class Classification",
    "两层架构": "Two-layer Architecture",
    "规则层": "Rule Layer",
    "跨场景": "Cross-scenario",
    "泛化能力": "Generalization",
    "正常": "Normal",
    "攻击": "Attack",
    "样本": "Samples",
    "时间窗口": "Time Window",
    "可视化": "Visualization",
    "保存模型": "Save Model",
    "加载数据": "Load Data",
    "导入库": "Import Libraries",
    "配置": "Configuration",
    "分布": "Distribution",
    "统计": "Statistics",
    "文件": "Files",
    "目录": "Directory",
    "路径": "Path",
    "处理": "Processing",
    "对齐": "Alignment",
    "标签": "Labels",
    "特征": "Features",
    "模型": "Models",
    "训练": "Training",
    "测试": "Testing",
    "验证": "Validation",
    "指标": "Metrics",
    "耗时": "Duration",
    "推理时间": "Inference Time",
    "大小": "Size",
    "数量": "Count",
    "比例": "Ratio",
    "均值": "Mean",
    "标准差": "Std Dev",
    "最大值": "Max",
    "最小值": "Min",
    "中位数": "Median",
    "熵": "Entropy",
    "功能码": "Function Code",
    "事务ID": "Transaction ID",
    "单元ID": "Unit ID",
    "源IP": "Source IP",
    "目标IP": "Destination IP",
    "端口": "Port",
    "包": "Packet",
    "窗口": "Window",
    "秒": "Seconds",
    "毫秒": "ms",
    "分钟": "Minutes",
    "小时": "Hours",
    "天": "Days",
    "周": "Weeks",
    "月": "Months",
    "年": "Years",
    "开始": "Start",
    "结束": "End",
    "完成": "Finished",
    "成功": "Success",
    "失败": "Failed",
    "错误": "Error",
    "警告": "Warning",
    "信息": "Info",
    "日志": "Log",
    "采样": "Sampling",
    "重采样": "Resampling",
    "过采样": "Oversampling",
    "欠采样": "Undersampling",
    "平衡": "Balanced",
    "权重": "Weights",
    "分类器": "Classifier",
    "随机森林": "Random Forest",
    "决策树": "Decision Tree",
    "逻辑回归": "Logistic Regression",
    "神经网络": "Neural Network",
    "多层感知机": "MLP",
    "梯度提升": "Gradient Boosting",
    "超参数": "Hyperparameters",
    "网格搜索": "Grid Search",
    "交叉验证": "Cross-validation",
    "特征选择": "Feature Selection",
    "特征工程": "Feature Engineering",
    "数据清洗": "Data Cleaning",
    "异常值": "Outliers",
    "缺失值": "Missing Values",
    "标准化": "Standardization",
    "归一化": "Normalization",
    "编码": "Encoding",
    "独热编码": "One-hot Encoding",
    "标签编码": "Label Encoding",
    "混淆矩阵": "Confusion Matrix",
    "分类报告": "Classification Report",
    "曲线": "Curve",
    "精度-召回率曲线": "PR Curve",
    "受试者工作特征曲线": "ROC Curve",
    "曲线下面积": "AUC",
    "重要性": "Importance",
    "贡献": "Contribution",
    "影响": "Impact",
    "对比": "Comparison",
    "改进": "Improvement",
    "优化": "Optimization",
    "部署": "Deployment",
    "边缘": "Edge",
    "实时": "Real-time",
    "轻量级": "Lightweight",
    "工业": "Industrial",
    "控制系统": "Control System",
    "协议": "Protocol",
    "网络": "Network",
    "流量": "Traffic",
    "捕获": "Capture",
    "数据集": "Dataset",
    "基准": "Baseline",
    "场景": "Scenario",
    "良性": "Benign",
    "外部": "External",
    "受损": "Compromised",
    "变电站": "Substation",
    "电力": "Power",
    "电网": "Grid",
    "设备": "Device",
    "智能电子设备": "IED",
    "监控": "Monitoring",
    "诊断": "Diagnostics",
    "预测": "Prediction",
    "检测": "Detection",
    "识别": "Identification",
    "分类": "Classification",
    "聚类": "Clustering",
    "回归": "Regression",
    "异常": "Anomaly",
    "入侵": "Intrusion",
    "攻击": "Attack",
    "威胁": "Threat",
    "防御": "Defense",
    "安全": "Security",
    "隐私": "Privacy",
    "信任": "Trust",
    "韧性": "Resilience",
    "可靠性": "Reliability",
    "可用性": "Availability",
    "完整性": "Integrity",
    "机密性": "Confidentiality",
    "认证": "Authentication",
    "加密": "Encryption",
    "解密": "Decryption",
    "密钥": "Key",
    "证书": "Certificate",
    "签名": "Signature",
    "验证": "Verification",
    "漏洞": "Vulnerability",
    "利用": "Exploit",
    "补丁": "Patch",
    "更新": "Update",
    "配置": "Configuration",
    "策略": "Policy",
    "规则": "Rule",
    "过滤": "Filtering",
    "防火墙": "Firewall",
    "网关": "Gateway",
    "代理": "Agent",
    "中间人": "Man-in-the-middle",
    "重放": "Replay",
    "拒绝服务": "DoS",
    "分布式拒绝服务": "DDoS",
    "注入": "Injection",
    "伪造": "Forgery",
    "篡改": "Tampering",
    "扫描": "Scanning",
    "侦察": "Reconnaissance",
    "暴力破解": "Brute Force",
    "写入": "Write",
    "读取": "Read",
    "线圈": "Coil",
    "离散输入": "Discrete Input",
    "保持寄存器": "Holding Register",
    "输入寄存器": "Input Register",
    "多个": "Multiple",
    "单个": "Single",
    "长度": "Length",
    "负载": "Payload",
    "有效载荷": "Payload",
    "时间戳": "Timestamp",
    "偏移": "Offset",
    "间隔": "Interval",
    "速率": "Rate",
    "吞吐量": "Throughput",
    "延迟": "Latency",
    "抖动": "Jitter",
    "丢包": "Packet Loss",
    "突发": "Burst",
    "强度": "Intensity",
    "多样性": "Diversity",
    "唯一": "Unique",
    "主": "Main",
    "从": "Slave",
    "服务器": "Server",
    "客户端": "Client",
    "主站": "Master",
    "从站": "Slave",
    "上位机": "HMI",
    "下位机": "PLC",
    "智能终端": "IED",
    "核心": "Core",
    "验证": "Validation",
    "发现": "Discovery",
    "结论": "Conclusion",
    "讨论": "Discussion",
    "展望": "Future Work",
    "致谢": "Acknowledgments",
    "引用": "Citation",
    "参考文献": "References",
    "附录": "Appendix",
    "图": "Figure",
    "表": "Table",
    "算法": "Algorithm",
    "代码": "Code",
    "实现": "Implementation",
    "工具": "Tool",
    "框架": "Framework",
    "平台": "Platform",
    "环境": "Environment",
    "设置": "Setup",
    "步骤": "Step",
    "说明": "Description",
    "指南": "Guide",
    "教程": "Tutorial",
    "示例": "Example",
    "演示": "Demo",
    "运行": "Run",
    "执行": "Execute",
    "输出": "Output",
    "输入": "Input",
    "参数": "Parameter",
    "变量": "Variable",
    "常量": "Constant",
    "函数": "Function",
    "类": "Class",
    "对象": "Object",
    "模块": "Module",
    "包": "Package",
    "库": "Library",
    "依赖": "Dependency",
    "版本": "Version",
    "更新": "Update",
    "修复": "Fix",
    "错误": "Bug",
    "调试": "Debug",
    "测试": "Test",
    "发布": "Release",
    "开源": "Open Source",
    "许可证": "License",
    "版权": "Copyright",
    "作者": "Author",
    "日期": "Date",
    "摘要": "Abstract",
    "引言": "Introduction",
    "相关工作": "Related Work",
    "方法": "Methodology",
    "实验": "Experiments",
    "结果": "Results",
    "讨论": "Discussion",
    "结论": "Conclusion"
}

def translate_text(text):
    if not text:
        return text
    # Replace based on map
    for cn, en in sorted(translation_map.items(), key=lambda x: len(x[0]), reverse=True):
        text = text.replace(cn, en)
    
    # Check if there are still Chinese characters
    if re.search(r'[\u4e00-\u9fff]', text):
        # If there are still Chinese characters, we might need a more aggressive approach
        # For now, let's just log it or do a simple regex replace for remaining ones if possible
        pass
    return text

def translate_notebook(file_path):
    if not file_path.exists():
        print(f"File not found: {file_path}")
        return

    print(f"Translating: {file_path.name}...")
    with open(file_path, 'r', encoding='utf-8') as f:
        nb = nbformat.read(f, as_version=4)

    for cell in nb.cells:
        if cell.cell_type == 'markdown':
            cell.source = translate_text(cell.source)
        elif cell.cell_type == 'code':
            # Translate comments in code cells
            lines = cell.source.split('\n')
            new_lines = []
            for line in lines:
                if '#' in line:
                    parts = line.split('#', 1)
                    comment = translate_text(parts[1])
                    new_lines.append(f"{parts[0]}# {comment}")
                else:
                    new_lines.append(line)
            cell.source = '\n'.join(new_lines)

    with open(file_path, 'w', encoding='utf-8') as f:
        nbformat.write(nb, f)
    print(f"Finished: {file_path.name}")

# List all notebooks to translate
all_notebooks = [f for f in os.listdir(notebook_dir) if f.endswith('.ipynb')]

for nb_name in all_notebooks:
    translate_notebook(notebook_dir / nb_name)
